### PR TITLE
Fix for Django 1.6 and AttributeError: 'Query' object has no attribute 'ordering_aliases'

### PR DESCRIPTION
**Pull request by shalakhin**
Checked the solution proposed at Issue #29 and it seems to work for me too. All thanks to @karanlyons

### CODE REVIEW

**Comment by dlo** [comment]
It would be great if this could be merged. Johnny Cache currently does not work on Django 1.6.

**Comment by jself** [comment]
Thanks for the pull request, doing this in a backwards compatible way though.
